name: binaryen
version: 0.0.6.0
synopsis: Haskell bindings to binaryen
description: Haskell bindings to [binaryen](https://github.com/WebAssembly/binaryen). Provides complete bindings to the C API, which can be useful for building WebAssembly toolchains in Haskell.
category: Compiler
maintainer: Cheng Shao <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/haskell-binaryen

extra-source-files:
  - binaryen/**/*
  - cbits/**/*
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - base < 5

flags:
  system-binaryen:
    description: Link against system-wide binaryen and don't build bundled binaryen
    manual: True
    default: False

internal-libraries:
  libbinaryen:
    extra-libraries:
      - pthread
      - stdc++
    when:
      - condition: flag(system-binaryen)
        then:
          extra-libraries:
            - binaryen
        else:
          include-dirs:
            - binaryen/src
            - binaryen/third_party/llvm-project/include
          cxx-options:
            - -D_GNU_SOURCE
            - -D_DEBUG
            - -D__STDC_CONSTANT_MACROS
            - -D__STDC_FORMAT_MACROS
            - -D__STDC_LIMIT_MACROS
            - -DBUILD_LLVM_DWARF
            - -std=c++14
            - -Wall
            - -Wextra
            - -Wno-unused-parameter
            - -Wno-implicit-int-float-conversion
            - -Wno-unknown-warning-option
            - -Wswitch
          cxx-sources:
            - binaryen/src/*.cpp
            - binaryen/src/asmjs/*.cpp
            - binaryen/src/cfg/*.cpp
            - binaryen/src/emscripten-optimizer/*.cpp
            - binaryen/src/ir/*.cpp
            - binaryen/src/passes/*.cpp
            - binaryen/src/support/*.cpp
            - binaryen/src/wasm/*.cpp
            - binaryen/third_party/llvm-project/**/*.cpp
    cc-options:
      - -std=c11
      - -Wall
      - -Wextra
    c-sources:
      - cbits/wrappers.c
    generated-other-modules:
      - Paths_binaryen

library:
  dependencies:
    - libbinaryen
  source-dirs: src
  generated-other-modules:
    - Paths_binaryen

tests:
  test:
    dependencies:
      - binaryen
    source-dirs: test
    generated-other-modules:
      - Paths_binaryen
    main: test.hs
    ghc-options: -threaded -rtsopts
