name: binaryen
version: 0.0.3.0
synopsis: Haskell bindings to binaryen
description: Haskell bindings to [binaryen](https://github.com/WebAssembly/binaryen). Provides complete bindings to the C API, which can be useful for building WebAssembly toolchains in Haskell.
category: Compiler
maintainer: Cheng Shao <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/haskell-binaryen

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

extra-libraries:
  - binaryen
  - stdc++

c-sources:
  - cbits/wrappers.c

ghc-options: -Wall

dependencies:
  - base < 5

library:
  source-dirs: src
