name: binaryen
version: 0.0.5.0
synopsis: Haskell bindings to binaryen
description: Haskell bindings to [binaryen](https://github.com/WebAssembly/binaryen). Provides complete bindings to the C API, which can be useful for building WebAssembly toolchains in Haskell.
category: Compiler
maintainer: Cheng Shao <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/haskell-binaryen

extra-source-files:
  - binaryen/**/*
  - CHANGELOG.md
  - LICENSE
  - README.md

extra-libraries:
  - stdc++

include-dirs:
  - binaryen/src
  - binaryen/third_party/llvm-project/include

cpp-options:
  - -DBUILD_LLVM_DWARF
  - -UNDEBUG

cxx-options:
  - -std=c++14
  - -Wall
  - -Wextra
  - -Wno-unused-parameter
  - -fno-omit-frame-pointer
  - -Wno-implicit-int-float-conversion
  - -Wno-unknown-warning-option
  - -Wswitch
  - -fPIC

cxx-sources:
  - binaryen/src/*.cpp
  - binaryen/src/asmjs/*.cpp
  - binaryen/src/cfg/*.cpp
  - binaryen/src/emscripten-optimizer/*.cpp
  - binaryen/src/ir/*.cpp
  - binaryen/src/passes/*.cpp
  - binaryen/src/support/*.cpp
  - binaryen/src/wasm/*.cpp
  - binaryen/third_party/llvm-project/**/*.cpp

cc-options:
  - -std=c11
  - -Wall
  - -Wextra
  - -fPIC

c-sources:
  - cbits/wrappers.c

ghc-options: -Wall

dependencies:
  - base < 5

library:
  source-dirs: src
  generated-other-modules:
    - Paths_binaryen
