name: pipeline

on:
  - push
  - pull_request

jobs:

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - uses: cachix/install-nix-action@v10
        with:
          skip_adding_nixpkgs_channel: true

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          mkdir ~/.stack
          printf "nix:\n  enable: true\n" > ~/.stack/config.yaml

          nix-shell --pure --run "stack test"
