name: pipeline

on:
  - push
  - pull_request

jobs:

  build:
    name: stack-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          stack-version: 2.3.3
          enable-stack: true
          stack-no-global: true

      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          stack test

  sdist:
    name: sdist
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          ghc-version: 8.10.2
          cabal-version: 3.2.0.0

      - name: checkout
        uses: actions/checkout@v2

      - name: sdist
        run: |
          cabal check
          cabal v2-sdist all

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist-newstyle/sdist/*.tar.gz

  haddock:
    name: haddock
    runs-on: ubuntu-20.04
    steps:

      - name: setup-haskell
        uses: actions/setup-haskell@main
        with:
          ghc-version: 8.10.2
          cabal-version: 3.2.0.0

      - name: checkout
        uses: actions/checkout@v2

      - name: haddock
        run: |
          cabal v2-haddock --haddock-for-hackage --haddock-hyperlink-source --haddock-quickjump all

      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: haddock
          path: dist-newstyle/*-docs.tar.gz
